%%
createFit(feature_downstairs(:,1));%figure();createFit(test_feature_downstairs(:,2));
createFit(feature_downstairs(:,2));
createFit(feature_downstairs(:,5));
createFit(feature_downstairs(:,51));
createFit(feature_downstairs(:,52));
createFit(feature_downstairs(:,55));
createFit(feature_downstairs(:,101));
createFit(feature_downstairs(:,102));
createFit(feature_downstairs(:,105));
createFit(feature_downstairs(:,151));
createFit(feature_downstairs(:,152));
createFit(feature_downstairs(:,155));
createFit(feature_downstairs(:,201));
createFit(feature_downstairs(:,202));
createFit(feature_downstairs(:,205));
createFit(feature_downstairs(:,251));
createFit(feature_downstairs(:,252));
createFit(feature_downstairs(:,255));
createFit(feature_downstairs(:,301));
createFit(feature_downstairs(:,302));
createFit(feature_downstairs(:,305));
%%
createFit(feature_elevatordown(:,1));
createFit(feature_elevatordown(:,2));
createFit(feature_elevatordown(:,5));
createFit(feature_elevatordown(:,51));
createFit(feature_elevatordown(:,52));
createFit(feature_elevatordown(:,55));
createFit(feature_elevatordown(:,101));
createFit(feature_elevatordown(:,102));
createFit(feature_elevatordown(:,105));
createFit(feature_elevatordown(:,151));
createFit(feature_elevatordown(:,152));
createFit(feature_elevatordown(:,155));
createFit(feature_elevatordown(:,201));
createFit(feature_elevatordown(:,202));
createFit(feature_elevatordown(:,205));
createFit(feature_elevatordown(:,251));
createFit(feature_elevatordown(:,252));
createFit(feature_elevatordown(:,255));
createFit(feature_elevatordown(:,301));
createFit(feature_elevatordown(:,302));
createFit(feature_elevatordown(:,305));

%%
createFit(feature_elevatorup(:,1));
createFit(feature_elevatorup(:,2));
createFit(feature_elevatorup(:,5));
createFit(feature_elevatorup(:,51));
createFit(feature_elevatorup(:,52));
createFit(feature_elevatorup(:,55));
createFit(feature_elevatorup(:,101));
createFit(feature_elevatorup(:,102));
createFit(feature_elevatorup(:,105));
createFit(feature_elevatorup(:,151));
createFit(feature_elevatorup(:,152));
createFit(feature_elevatorup(:,155));
createFit(feature_elevatorup(:,201));
createFit(feature_elevatorup(:,202));
createFit(feature_elevatorup(:,205));
createFit(feature_elevatorup(:,251));
createFit(feature_elevatorup(:,252));
createFit(feature_elevatorup(:,255));
createFit(feature_elevatorup(:,301));
createFit(feature_elevatorup(:,302));
createFit(feature_elevatorup(:,305));

%%
createFit(feature_lying(:,1));
createFit(feature_lying(:,2));
createFit(feature_lying(:,5));
createFit(feature_lying(:,51));
createFit(feature_lying(:,52));
createFit(feature_lying(:,55));
createFit(feature_lying(:,101));
createFit(feature_lying(:,102));
createFit(feature_lying(:,105));
createFit(feature_lying(:,151));
createFit(feature_lying(:,152));
createFit(feature_lying(:,155));
createFit(feature_lying(:,201));
createFit(feature_lying(:,202));
createFit(feature_lying(:,205));
createFit(feature_lying(:,251));
createFit(feature_lying(:,252));
createFit(feature_lying(:,255));
createFit(feature_lying(:,301));
createFit(feature_lying(:,302));
createFit(feature_lying(:,305));

%%
createFit(feature_sitting(:,1));
createFit(feature_sitting(:,2));
createFit(feature_sitting(:,5));
createFit(feature_sitting(:,51));
createFit(feature_sitting(:,52));
createFit(feature_sitting(:,55));
createFit(feature_sitting(:,101));
createFit(feature_sitting(:,102));
createFit(feature_sitting(:,105));
createFit(feature_sitting(:,151));
createFit(feature_sitting(:,152));
createFit(feature_sitting(:,155));
createFit(feature_sitting(:,201));
createFit(feature_sitting(:,202));
createFit(feature_sitting(:,205));
createFit(feature_sitting(:,251));
createFit(feature_sitting(:,252));
createFit(feature_sitting(:,255));
createFit(feature_sitting(:,301));
createFit(feature_sitting(:,302));
createFit(feature_sitting(:,305));

%%
createFit(feature_standing(:,1));
createFit(feature_standing(:,2));
createFit(feature_standing(:,5));
createFit(feature_standing(:,51));
createFit(feature_standing(:,52));
createFit(feature_standing(:,55));
createFit(feature_standing(:,101));
createFit(feature_standing(:,102));
createFit(feature_standing(:,105));
createFit(feature_standing(:,151));
createFit(feature_standing(:,152));
createFit(feature_standing(:,155));
createFit(feature_standing(:,201));
createFit(feature_standing(:,202));
createFit(feature_standing(:,205));
createFit(feature_standing(:,251));
createFit(feature_standing(:,252));
createFit(feature_standing(:,255));
createFit(feature_standing(:,301));
createFit(feature_standing(:,302));
createFit(feature_standing(:,305));

%%
createFit(feature_upstairs(:,1));
createFit(feature_upstairs(:,2));
createFit(feature_upstairs(:,5));
createFit(feature_upstairs(:,51));
createFit(feature_upstairs(:,52));
createFit(feature_upstairs(:,55));
createFit(feature_upstairs(:,101));
createFit(feature_upstairs(:,102));
createFit(feature_upstairs(:,105));
createFit(feature_upstairs(:,151));
createFit(feature_upstairs(:,152));
createFit(feature_upstairs(:,155));
createFit(feature_upstairs(:,201));
createFit(feature_upstairs(:,202));
createFit(feature_upstairs(:,205));
createFit(feature_upstairs(:,251));
createFit(feature_upstairs(:,252));
createFit(feature_upstairs(:,255));
createFit(feature_upstairs(:,301));
createFit(feature_upstairs(:,302));
createFit(feature_upstairs(:,305));

%%
createFit(feature_walking(:,1));
createFit(feature_walking(:,2));
createFit(feature_walking(:,5));
createFit(feature_walking(:,51));
createFit(feature_walking(:,52));
createFit(feature_walking(:,55));
createFit(feature_walking(:,101));
createFit(feature_walking(:,102));
createFit(feature_walking(:,105));
createFit(feature_walking(:,151));
createFit(feature_walking(:,152));
createFit(feature_walking(:,155));
createFit(feature_walking(:,201));
createFit(feature_walking(:,202));
createFit(feature_walking(:,205));
createFit(feature_walking(:,251));
createFit(feature_walking(:,252));
createFit(feature_walking(:,255));
createFit(feature_walking(:,301));
createFit(feature_walking(:,302));
createFit(feature_walking(:,305));




